webempresa/core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.home,name='home'),
    path('about/', views.about,name='about'),
    path('services/', views.services,name='services'),
    path('store/', views.store,name='store'),
    path('contact/', views.contact,name='contact'),
    path('blog/', views.blog,name='blog'),
    path('sample/', views.sample,name='sample'),
]

webempresa/webempresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

webempresa/core/models.py
from django.db import models

# Create your models here.

webempresa/services/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    title = models.CharField("titulo",max_length=200)
    subtitle = models.CharField("subtitulo",max_length=200)
    content = models.TextField("contenido")
    image = models.ImageField("image",upload_to="services")
    created = models.DateTimeField("fecha de creación",auto_now_add=True)
    updated = models.DateTimeField("fecha de edición",auto_now=True)

    class Meta:
        verbose_name = "servicio"
        verbose_name_plural = "servicios"
        ordering = ['-created']

    def __str__(self):
        return self.title

webempresa/core/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def home(requets):
    return render(requets,'core/home.html')

def about(requets):
    return render(requets,'core/about.html')

def services(requets):
    return render(requets,'core/services.html')

def store(requets):
    return render(requets,'core/store.html')

def contact(requets):
    return render(requets,'core/contact.html')

def blog(requets):
    return render(requets,'core/blog.html')

def sample(requets):
    return render(requets,'core/sample.html')

webempresa/services/views.py
from django.shortcuts import render

# Create your views here.

webempresa/core/templates/core/about.html
{% extends "core/base/index.html" %}
{% load static %}
{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="img/about.jpg" alt="">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Tradición familiar italiana</span>
              <span class="section-heading-lower">Nuestra historia</span>
            </h2>
            <p>Fundada en 1987 consectetur adipiscing elit. Donec leo dui, vehicula vel dapibus ac, tempus non enim. Nunc tempor vel lacus vel gravida. Nam sit amet pellentesque mi. </p>
            <p>Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui.Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

webempresa/core/templates/core/base/footer.html
<footer class="footer text-faded text-center py-5">
    <div class="container">
      <p class="m-0">
          <a href="#" class="link">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
            </span>
          </a>
          <a href="#" class="link">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
            </span>
          </a>
          <a href="#" class="link">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
            </span>
          </a>
        </p>
      <p class="m-0 mbt">
          <a href="{% url "core:sample" %}" class="link">Política de privacidad</a> ·
          <a href="{% url "core:sample" %}" class="link">Aviso legal</a> ·
          <a href="{% url "core:sample" %}" class="link">Cookies</a>
          </p>
      <p class="m-0 mbt1">&copy; La Caffettiera 2018</p>
    </div>
</footer>

webempresa/core/templates/core/base/header.html
<h1 class="site-heading text-center text-white d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3">L'autentico caffè d'italia</span>
    <span class="site-heading-lower">La Caffettiera</span>
</h1>

  <!-- Navegación -->
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url "core:home" %}">La Caffettiera</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mx-auto">
                
            <li class="nav-item px-lg-4 {% if request.path == '/' %}active{% endif %}">
                <a class="nav-link text-uppercase text-expanded" href="{% url "core:home" %}">Inicio</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path == '/about/' %}active{% endif %}">
                <a class="nav-link text-uppercase text-expanded" href="{% url "core:about" %}">Historia</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path == '/services/' %}active{% endif %}">
                <a class="nav-link text-uppercase text-expanded" href="{% url "core:services" %}">Servicios</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path == '/store/' %}active{% endif %}">
                <a class="nav-link text-uppercase text-expanded" href="{% url "core:store" %}">Visítanos</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path == '/contact/' %}active{% endif %}">
                <a class="nav-link text-uppercase text-expanded" href="{% url "core:contact" %}">Contacto</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path == '/blog/' %}active{% endif %}">
                <a class="nav-link text-uppercase text-expanded" href="{% url "core:blog" %}">Blog</a>
            </li>
            </ul>
        </div>
    </div>
</nav>

webempresa/core/templates/core/base/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Inicio | La Caffettiera</title>

    <!-- Bootstrap -->
    <link href="{% static "core/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Fuentes -->
    <link href="{% static "core/vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Estilos -->
    <link href="{% static "core/css/business-casual.css" %}" rel="stylesheet">

  </head>
  <body>
    <!-- header -->
    {% include "core/base/header.html" %}

    <!-- content -->
    {% block content %}
    
    {% endblock content %}

    <!-- Pié de página -->
    {% include "core/base/footer.html" %}

    <!-- Bootstrap -->
    <script src="{% static "core/vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "core/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>

webempresa/core/templates/core/blog.html
{% extends "core/base/index.html" %}
{% load static %}
{% block content %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-innerv text-center rounded">
          <h2 class="section-heading mb-5">
            <span class="section-heading-upper">17/05/2000</span>
            <span class="section-heading-lower">Ofertas de otoño</span>
          </h2>
          <p class="mb-0">
            <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="img/products-01.jpg" alt="">
          </p>
          <p class="mb-0 mbt">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec leo dui, vehicula vel dapibus ac, tempus non enim. Nunc tempor vel lacus vel gravida. Nam sit amet pellentesque mi. Aliquam eget porta mi, quis fermentum metus. Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui. Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.
          </p>
          <p class="mb-0 mbt">
            <span class="section-heading-under">Publicado por <em><b>Juan</b></em> en <em><a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em></span>
          </p>
        </div>

      </div>
    </div>
  </div>
</section>
{% endblock content %}

webempresa/core/templates/core/contact.html
{% extends "core/base/index.html" %}
{% load static %}
{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="img/contact.jpg" alt="">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Envíanos tus dudas</span>
              <span class="section-heading-lower">Contacto</span>
            </h2>

            <!-- Formulario de contacto -->
            <form>
                <div class="form-group">
                    <label>Nombre *</label>
                    <div class="input-group">
                        <input type="text" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label>Email *</label>
                    <div class="input-group">
                        <input type="text" class="form-control">
                    </div>
                    <ul class="errorlist">
                        <li>El email no es correcto.</li>
                    </ul>
                </div>
                <div class="form-group">
                    <label>Mensaje *</label>
                    <div class="input-group">
                        <textarea class="form-control"></textarea>
                    </div>
                </div>
                <div class="text-center">
                    <input type="submit" class="btn btn-primary btn-block py-2" value="Enviar">
                </div>
            </form>
            <!-- Fin formulario de contacto -->

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

webempresa/core/templates/core/home.html
{% extends "core/base/index.html" %}
{% load static %}
{% block content %}
  <!-- Cabecera -->
  <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static "core/img/intro.jpg" %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Déjate sorprender</span>
            <span class="section-heading-lower">Te gustará</span>
          </h2>
          <p class="mb-3">Trabajamos sólo con los mejores ingredientes. Una vez lo pruebes, nuestro café será la mejor forma de empezar tu rutina diaria.
          </p>
          <div class="intro-button mx-auto">
            <a class="btn btn-primary btn-xl" href="store.html">Visítanos</a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Mensaje -->
  <section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="cta-inner text-center rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Compromiso total</span>
              <span class="section-heading-lower">Garantizado</span>
            </h2>
            <p class="mb-0">Sed pulvinar blandit elit id venenatis. Ut eget lacus neque. Nullam justo quam, efficitur nec turpis vitae, efficitur posuere ligula. Proin ut turpis orci. Aenean porta sodales lectus faucibus pellentesque. In sed felis iaculis, rhoncus felis a, maximus mi.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

webempresa/core/templates/core/sample.html
{% extends "core/base/index.html" %}
{% load static %}
{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <div class="about-heading-content mbtm">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5 forced">
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower">Página genérica</span>
            </h2>
            <div class="section-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ipsum nulla, scelerisque sed dui eu, fringilla consequat velit. Integer euismod, eros sit amet facilisis rutrum, elit massa iaculis ex, vitae gravida velit dolor at nunc. Proin tincidunt pellentesque lacus. Cras egestas ligula eu purus finibus, et convallis sem rhoncus. Fusce porta magna nisl. Aenean sed quam at tellus sollicitudin facilisis. Pellentesque eleifend placerat luctus.</p>
                <p>Proin semper nisi quam, faucibus pharetra sapien laoreet et. Proin sit amet aliquam mi. Aliquam rhoncus tortor a accumsan condimentum. Maecenas nisl urna, auctor vel aliquam ut, accumsan sit amet ipsum. Nulla at felis lorem. Phasellus sit amet consectetur lacus. Praesent eget feugiat sem. Nam odio neque, luctus quis velit sagittis, aliquet consequat arcu. Duis eget molestie turpis, nec mattis sem. Donec sem risus, rutrum quis elementum ut, pulvinar et lorem. Quisque egestas justo id justo sodales, id commodo lorem condimentum.</p>
                <p>Mauris hendrerit felis id diam pellentesque, vel lobortis lectus sagittis. Proin efficitur dui justo, sed laoreet mi sollicitudin dapibus. Donec a convallis lorem. Sed laoreet suscipit gravida. Nam tincidunt in justo sit amet rhoncus. Donec et lectus est. Mauris a felis eu risus tincidunt congue ac sit amet orci. Nam placerat varius elit, eu vulputate nibh consequat eget.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

webempresa/core/templates/core/services.html
{% extends "core/base/index.html" %}
{% load static %}
{% block content %}
<section class="page-section">
  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex mr-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-upper">La mezcla perfecta</span>
            <span class="section-heading-lower">Cafés y tés</span>
          </h2>
        </div>
      </div>
      <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="img/products-01.jpg" alt="">
      <div class="product-item-description d-flex ml-auto">
        <div class="bg-faded p-5 rounded">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In massa purus, posuere non neque sed, ultricies ornare magna. Donec eu lobortis ex. Morbi maximus tempor accumsan. Mauris pellentesque mauris id nibh vestibulum, id sodales lorem bibendum. Nunc at interdum velit. Donec nec sapien eget arcu imperdiet bibendum</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="page-section">
  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex mr-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-upper">El mejor acompañamiento</span>
            <span class="section-heading-lower">Bollería artesanal</span>
          </h2>
        </div>
      </div>
      <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="img/products-02.jpg" alt="">
      <div class="product-item-description d-flex ml-auto">
        <div class="bg-faded p-5 rounded">
          <p class="mb-0">Morbi dapibus malesuada mollis. Nunc cursus velit eget cursus pharetra. Ut feugiat, dui id congue porttitor, sem erat pharetra dui, in ullamcorper quam nulla vitae quam. Sed blandit libero feugiat diam cursus, nec euismod ante consequat. Curabitur nec tincidunt ipsum, in tempor turpis. Sed ut metus a nisl rhoncus placerat.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="page-section">
  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex mr-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-upper">Producto certificado</span>
            <span class="section-heading-lower">También vendemos</span>
          </h2>
        </div>
      </div>
      <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="img/products-03.jpg" alt="">
      <div class="product-item-description d-flex ml-auto">
        <div class="bg-faded p-5 rounded">
          <p class="mb-0">Integer ac elementum lacus, consectetur cursus tellus. Suspendisse faucibus sapien massa, ac pharetra est aliquet a. In interdum feugiat ultrices. Aliquam eget tempor libero. Aliquam sit amet ante quis lectus fermentum bibendum. Ut molestie nulla in tellus euismod feugiat. Nunc varius erat nulla, eu dictum mi ultrices in.</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

webempresa/core/templates/core/store.html
{% extends "core/base/index.html" %}
{% load static %}
{% block content %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner text-center rounded">
          <h2 class="section-heading mb-5">
            <span class="section-heading-upper">Te esperamos</span>
            <span class="section-heading-lower">Visítanos</span>
          </h2>
          <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
            <li class="list-unstyled-item list-hours-item d-flex">
              Lunes a viernes
              <span class="ml-auto">7:00 a 20:00</span>
            </li>
            <li class="list-unstyled-item list-hours-item d-flex">
              Sábados
              <span class="ml-auto">9:00 a 17:00</span>
            </li>
            <li class="list-unstyled-item list-hours-item d-flex">
              Domingos
              <span class="ml-auto">Cerrado</span>
            </li>
          </ul>
          <p class="address mb-5">
            <em>
              <strong>Avd. Infusiones nº 127</strong>
              <br>
              Barcelona
            </em>
          </p>
          <p class="mb-0">
            <small>
              <em>Llámanos y pregunta</em>
            </small>
            <br>
            (317) 585-8468
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}